BookTrader/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('trader.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('profile/', views.myprofile, name="myprofile"),
    path('profile/<int:id>/', views.profile, name='profile'),
]

trader/urls.py
from django.urls import path
from . import views

app_name = 'trader'
urlpatterns = [
    path('', views.index, name="index"),
    path('advertisement-create/', views.advertisement_create, name='advertisement-creat'),
    path('advertisement/<int:id>/report', views.report, name='report'),
    path('advertisement/<int:adv_id>', views.advertisement, name='advertisement')
]

accounts/models.py
from django.db import models

# Create your models here.

trader/models.py
from django.contrib.auth.models import User
from django.db import models


class Book(models.Model):
    """
    Model of book that contains information about book like: author name, book title, ISBN, publication date
    """
    # Author name
    author = models.CharField(max_length=50)
    # Book title
    title = models.CharField(max_length=50)
    # ISBN
    isbn = models.CharField(max_length=50)
    # Publication date
    publication_date = models.DateField('publication_date')

    def __str__(self):
        """
        Method returns Book Title
        :return: Book Title
        """
        return self.title


class Advertisement(models.Model):
    """
    Model of Advertisement, contains information like: advertisement tile, description, date of publication and date of expiration.
    """
    title = models.CharField(max_length=50)
    description = models.TextField()
    creater = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    # TODO location here
    date_of_publication = models.DateField()
    date_of_expiration = models.DateField()

    def __str__(self):
        return self.title


class Report(models.Model):
    """
    Model of report, contains information like: which advertisement is for, date of report, description, and reporting user.
    """
    advertisement = models.ForeignKey(Advertisement, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    report_date = models.DateTimeField('report_date')
    description = models.TextField()

    def __str__(self):
        """
        Method returns reported advertisement name
        :return: reported advertisement name
        """
        return self.advertisement


class Avatar(models.Model):
    """
    Model of avatar, contains avatar image and Foreign Key to user who have this avatar.
    """
    image = models.ImageField('avatar')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """
        Method returns username of avatar owner.
        :return: username of avatar owner
        """
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class Register_form(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password', 'email', 'first_name', 'last_name')


class Login_form(forms.Form):
    username = forms.CharField(label='username', max_length=120)
    password = forms.CharField(label='password', max_length=120, widget=forms.PasswordInput())

trader/forms.py
from django import forms
from .models import Report, Advertisement

class Report_form(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('description',)

class AdvertisementCreat_form(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ('title', 'description')

accounts/views.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import Register_form, Login_form
from django.http import Http404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


def register(request):
    if request.method == "POST":
        form = Register_form(request.POST)
        if form.is_valid():
            user = form.save(commit=True)
            return redirect('login')
        else:
            return render(request, 'accounts/register.html', {'form': form})
    else:
        form = Register_form()
        return render(request, 'accounts/register.html', {'form': form})


def login(request):
    if request.method == "POST":
        form = Login_form(request.POST)
        if form.is_valid():
            user = authenticate(username=request.POST['username'], password=request.POST['password'])
            if user is not None:
                return HttpResponse('loged in, welcome')
            else:
                return render(request, 'accounts/login.html', {'form': Login_form()})

        else:
            return render(request, 'accounts/login.html', {'form': Login_form()})

    else:
        return render(request, 'accounts/login.html', {'form': Login_form()})

def myprofile(request):
    return render(request, 'accounts/profile.html', {'user': request.user})

def profile(request, id):
    try:
        user = User.objects.get(pk=id)
    except User.DoesNotExist:
        raise Http404('Nie ma takiego usera')
    return render(request, 'accounts/profile.html', {'user': user})

trader/views.py
from django.http import Http404
from django.shortcuts import render
from .forms import Report_form, AdvertisementCreat_form
from .models import Advertisement


def index(request):
    return render(request, 'index.html')


def report(request, id):
    return render(request, 'report.html', {'form': Report_form()})


def advertisement(request, adv_id):
    try:
        adv = Advertisement.objects.get(pk=adv_id)
    except Advertisement.DoesNotExist:
        raise Http404("ogłoszenie nie istnieje ")
    return render(request, 'advertisement.html', {'advertisement': adv})


def advertisement_create(request):
    return render(request, 'advertisement-create.html', {'form': AdvertisementCreat_form()})

accounts/templates/accounts/base.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Pacifico|Open+Sans" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'trader/style.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-tob custom-navbar">
                <a class="navbar-brand" id="booktrade" href="#">Booktrade</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                    <a class="nav-item nav-link" href="#">Add book</a>
                    <a class="nav-item nav-link" href="#">About us</a>
                    <a class="nav-item nav-link" href="#">Login</a>
                    <a class="nav-item nav-link" href="#">Register</a>
                </div>
                </div>
            </nav>
    {% block body %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block head %}

{% endblock %}
{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Zaloguj">
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}

{% block head %}
    <title>Profil {{ user.username }}</title>
{% endblock %}
{% block body %}
    <h1>{{ user.username }}</h1>
    <br>
    <ul>
        {% for a in user.advertisement_set.all %}
            <li><a href="{% url 'trader:advertisement' a.id %}">{{ a.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="zarejestruj">
    </form>
{% endblock %}

trader/templates/advertisement-create.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
    <h1>Tworzenie ogłoszenia</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Stwórz">
    </form>
{% endblock %}

trader/templates/advertisement.html
{% extends 'base.html' %}
{% block body %}
<h1>{{ advertisement.title }}</h1>
    <ul>
        <li>{{ advertisement.creater }}</li>
    <br>
    <li>{{ advertisement.description }}</li>
    <li>{{ advertisement.date_of_publication }}</li>
        <li>{{ advertisement.date_of_expiration }}</li>
    </ul>
{% endblock %}

trader/templates/base.html
{% load static %}
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Pacifico|Open+Sans" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'trader/style.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
        <nav class="custom-navbar navbar navbar-expand-lg navbar-light bg-light fixed-top ">
                <a class="navbar-brand" id="booktrade" href="#">Booktrade</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                    <a class="nav-item nav-link" href="#">Add book</a>
                    <a class="nav-item nav-link" href="#">About us</a>
                    <a class="nav-item nav-link" href="#">Login</a>
                    <a class="nav-item nav-link" href="#">Register</a>
                </div>
                </div>
            </nav>
    {% block body %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

trader/templates/index.html
{% extends 'base.html' %}
{% block body %}
<h1>Hello, all works just fine!</h1>
{% endblock %}

trader/templates/report.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
    <h1>Zgłoszenie</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Zgłoś">
    </form>
{% endblock %}